spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    max-active: 50
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: root
#    url: jdbc:postgresql://localhost/postgres
#    platform: postgres
#    initialization-mode: always
#    continue-on-error: true
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    database: postgresql